In [1]:
# ==============================================================================================================
# The following snippet demonstrates various camera properties
# ==============================================================================================================

import math
import torch
import numpy as np
from kaolin.render.camera import Camera

In [2]:
device = 'cuda'

camera = Camera.from_args(
    eye=torch.tensor([4.0, 4.0, 4.0]),
    at=torch.tensor([0.0, 0.0, 0.0]),
    up=torch.tensor([0.0, 1.0, 0.0]),
    fov=30 * np.pi / 180,  # In radians
    width=800, height=800,
    dtype=torch.float32,
    device=device
)

print(camera.width)
print(camera.height)
print(camera.lens_type)

print(camera.device)
camera = camera.cpu()
print(camera.device)

# Create a batched camera and view single element
camera = Camera.cat((camera, camera))
print(camera)
camera = camera[0]
print(camera)

print(camera.dtype)
camera = camera.half()
print(camera.dtype)
camera = camera.double()
print(camera.dtype)
camera = camera.float()
print(camera.dtype)

print(camera.extrinsics.requires_grad)
print(camera.intrinsics.requires_grad)

print(camera.to('cuda', torch.float64))

800
800
pinhole
cuda:0
cpu
CameraExtrinsics of 2 cameras, of coordinate system: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0'). 
Camera #0 View Matrix: 
tensor([[[ 0.7071,  0.0000, -0.7071,  0.0000],
         [-0.4082,  0.8165, -0.4082,  0.0000],
         [ 0.5774,  0.5774,  0.5774, -6.9282],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[ 0.7071,  0.0000, -0.7071,  0.0000],
         [-0.4082,  0.8165, -0.4082,  0.0000],
         [ 0.5774,  0.5774,  0.5774, -6.9282],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]]),
Camera #0 Inverse View Matrix: 
tensor([[[ 0.7071, -0.4082,  0.5774,  4.0000],
         [ 0.0000,  0.8165,  0.5774,  4.0000],
         [-0.7071, -0.4082,  0.5774,  4.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]],

        [[ 0.7071, -0.4082,  0.5774,  4.0000],
         [ 0.0000,  0.8165,  0.5774,  4.0000],
         [-0.7071, -0.4082,  0.5774,  4.0000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]])

Camera #1 View 